# Generated by Django 4.0.5 on 2022-10-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashborad.course'),
        ),
    ]
