# Generated by Django 4.1.2 on 2022-10-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('students', models.ManyToManyField(related_name='Студенты', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('teacher', models.ManyToManyField(related_name='Преподаватели', to=settings.AUTH_USER_MODEL, verbose_name='Преподавательcкий состав')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lecture', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course', verbose_name='Название курса')),
            ],
        ),
    ]
