# Generated by Django 4.1.2 on 2022-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_course_options_alter_lecture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
