# Generated by Django 4.1.2 on 2022-10-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_course_slug_lecture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='pictures/mirea_maskot.png', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default='', verbose_name='Время публикации лекции'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
