# Generated by Django 4.1.2 on 2022-10-26 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_course_picture_alter_course_slug_alter_lecture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации лекции'),
        ),
    ]
