# Generated by Django 4.1.2 on 2022-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='firstname',
            field=models.CharField(default='', max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия пользователя'),
        ),
    ]
