# Generated by Django 4.1.2 on 2022-10-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdata_firstname_alter_userdata_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='picture',
            field=models.ImageField(default='pictures/mirea_maskot.png', upload_to='pictures'),
        ),
    ]
