# Generated by Django 4.1.2 on 2022-10-26 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userdata_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL),
        ),
    ]
